name: Release to PyPi

on:
  release:
    types:
      - published

concurrency:
  cancel-in-progress: true
  group: release-${{ github.ref }}

jobs:
  release:
    name: Release to PyPi
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install Deps
        run: pip install -r ./requirements/dev.txt
      - name: Build
        run: python setup.py sdist
      - name: Release
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
